### ISSUE TITLE
Support subdomain under authoritative zone for DNS challenge

### ISSUE THREAD

**Issue by MyAnoneNeko** [libdns/desec#1]
For context sub.example.dedyn.io DNS name belongs to example.dedyn.io authoritative zone. In caddy, while trying to solve DNS challenge the deSEC libns tries to make a record under sub.example.dedyn.io instead of example.dedyn.io resulting in 
```RRSets: unexpected status code 404: {\"detail\":\"Not found.\"}```

May you update deSEC provider to support subdomain? For this case, I believe deSEC provider should send a record to example.dedyn.io with with a subname value of _acme-challenge.sub

https://desec.readthedocs.io/en/latest/dns/domains.html#identifying-the-responsible-domain-for-a-dns-name

Snippet of caddy error logs:
```
2023/08/21 23:26:50.273 INFO    tls.issuance.zerossl.acme_client        trying to solve challenge       
{
    "identifier": "*.sub.example.dedyn.io",
    "challenge_type": "dns-01",
    "ca": "https://acme-staging-v02.api.letsencrypt.org/directory"
}
2023/08/21 23:26:51.180 ERROR   tls.issuance.zerossl.acme_client        cleaning up solver      
{
    "identifier": "*.sub.example.dedyn.io",
    "challenge_type": "dns-01",
    "error": "no memory of presenting a DNS record for \"_acme-challenge.sub.example.dedyn.io\" (usually OK if presenting also failed)"
}
2023/08/21 23:26:51.234 ERROR   tls.obtain      could not get certificate from issuer   
{
    "identifier": "*.sub.example.dedyn.io",
    "issuer": "acme-staging-v02.api.letsencrypt.org-directory",
    "error": "[*.sub.example.dedyn.io] solving challenges: presenting for challenge: adding temporary record for zone \"_acme-challenge.sub.example.dedyn.io.\": writing RRSets: unexpected status code 404: {\"detail\":\"Not found.\"} (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/115592954/10422849924) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"
}
2023/08/21 23:26:51.235 ERROR   tls.obtain      will retry      
{
    "error": "[*.sub.example.dedyn.io] Obtain: [*.sub.example.dedyn.io] solving challenges: presenting for challenge: adding temporary record for zone \"_acme-challenge.sub.example.dedyn.io.\": writing RRSets: unexpected status code 404: {\"detail\":\"Not found.\"} (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/115592954/10422849924) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)",
    "attempt": 1,
    "retrying_in": 60,
    "elapsed": 3.0121087,
    "max_duration": 2592000
}

```

**Comment by znkr** [comment]
Thanks for filling this issue. Unfortunately, it's a bit more complicated: libdns is not responsible for identifying which zone (sub.example.dedyn.io or example.dedyn.io) to add a challenge to. That's the job of CertMagic which uses DNS SOA records for this purpose. Your problem sounds like something is going wrong here. Could you share the DNS configuration? I'll try to find some time to reproduce it.

**Comment by MyAnoneNeko** [comment]
My zone is below. The NS ips subdomain record points to a [DNS service that returns the embedded IP address](https://sslip.io/). For privacy reasons the A record was change from my server IP and the domain was changed to example.
```
; Zonefile for example.dedyn.io exported from desec.io at 2023-08-23 03:02:39.825591+00:00
*.example.dedyn.io.	3600	IN	CNAME	example.dedyn.io.
example.dedyn.io.	60	IN	A	127.0.0.1
example.dedyn.io.	3600	IN	NS	ns1.desec.io.
example.dedyn.io.	3600	IN	NS	ns1.desec.org.
example.dedyn.io.	300	IN	SOA	get.desec.io. get.desec.io. 2023082311 86400 3600 2419200 3600
ips.example.dedyn.io.	3600	IN	NS	ns-aws.sslip.io.
ips.example.dedyn.io.	3600	IN	NS	ns-azure.sslip.io.
ips.example.dedyn.io.	3600	IN	NS	ns-gce.sslip.io.
```

**Comment by znkr** [comment]
I tried reproducing this with libdns only by adding tests for subdomains (https://github.com/libdns/desec/commit/953bed94708dff0b58b030cca729be0334997859) but that didn't reproduce the issue. I addition I improved the error message to understand the problem better (https://github.com/libdns/desec/commit/ddb7ad128b0e053ee8b930700061f9b14e74a347). Maybe that can help in figuring out what's going on.

Could you give it a try with the new version and report the error you are seeing?

**Comment by MyAnoneNeko** [comment]
Here's the errors log with v0.2.3
```
2023/08/24 03:47:49.296 INFO    tls.issuance.zerossl.acme_client        trying to solve challenge       {"identifier": "*.ips.example.dedyn.io", "challenge_type": "dns-01", "ca": "https://acme-staging-v02.api.letsencrypt.org/directory"}
2023/08/24 03:47:49.764 ERROR   tls.issuance.zerossl.acme_client        cleaning up solver      {"identifier": "*.ips.example.dedyn.io", "challenge_type": "dns-01", "error": "no memory of presenting a DNS record for \"_acme-challenge.ips.example.dedyn.io\" (usually OK if presenting also failed)"}
2023/08/24 03:47:49.818 ERROR   tls.obtain      could not get certificate from issuer   {"identifier": "*.ips.example.dedyn.io", "issuer": "acme-staging-v02.api.letsencrypt.org-directory", "error": "[*.ips.example.dedyn.io] solving challenges: presenting for challenge: adding temporary record for zone \"_acme-challenge.ips.example.dedyn.io.\": appending RRSets to zone \"_acme-challenge.ips.example.dedyn.io.\": unexpected status code 404: {\"detail\":\"Not found.\"} (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/115896424/10467017264) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
2023/08/24 03:47:49.818 ERROR   tls.obtain      will retry      {"error": "[*.ips.example.dedyn.io] Obtain: [*.ips.example.dedyn.io] solving challenges: presenting for challenge: adding temporary record for zone \"_acme-challenge.ips.example.dedyn.io.\": appending RRSets to zone \"_acme-challenge.ips.example.dedyn.io.\": unexpected status code 404: {\"detail\":\"Not found.\"} (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/115896424/10467017264) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)", "attempt": 1, "retrying_in": 60, "elapsed": 2.5339131, "max_duration": 2592000}
2023/08/24 03:48:49.820 INFO    tls.obtain      obtaining certificate   {"identifier": "*.ips.example.dedyn.io"}
2023/08/24 03:48:49.993 INFO    tls.issuance.acme.acme_client   trying to solve challenge       {"identifier": "*.ips.example.dedyn.io", "challenge_type": "dns-01", "ca": "https://acme-staging-v02.api.letsencrypt.org/directory"}
2023/08/24 03:48:50.449 ERROR   tls.issuance.acme.acme_client   cleaning up solver      {"identifier": "*.ips.example.dedyn.io", "challenge_type": "dns-01", "error": "no memory of presenting a DNS record for \"_acme-challenge.ips.example.dedyn.io\" (usually OK if presenting also failed)"}
2023/08/24 03:48:50.504 ERROR   tls.obtain      could not get certificate from issuer   {"identifier": "*.ips.example.dedyn.io", "issuer": "acme-staging-v02.api.letsencrypt.org-directory", "error": "[*.ips.example.dedyn.io] solving challenges: presenting for challenge: adding temporary record for zone \"_acme-challenge.ips.example.dedyn.io.\": appending RRSets to zone \"_acme-challenge.ips.example.dedyn.io.\": unexpected status code 404: {\"detail\":\"Not found.\"} (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/115896424/10467030484) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
2023/08/24 03:48:50.675 INFO    tls.issuance.zerossl.acme_client        trying to solve challenge       {"identifier": "*.ips.example.dedyn.io", "challenge_type": "dns-01", "ca": "https://acme-staging-v02.api.letsencrypt.org/directory"}
2023/08/24 03:48:51.148 ERROR   tls.issuance.zerossl.acme_client        cleaning up solver      {"identifier": "*.ips.example.dedyn.io", "challenge_type": "dns-01", "error": "no memory of presenting a DNS record for \"_acme-challenge.ips.example.dedyn.io\" (usually OK if presenting also failed)"}
2023/08/24 03:48:51.202 ERROR   tls.obtain      could not get certificate from issuer   {"identifier": "*.ips.example.dedyn.io", "issuer": "acme-staging-v02.api.letsencrypt.org-directory", "error": "[*.ips.example.dedyn.io] solving challenges: presenting for challenge: adding temporary record for zone \"_acme-challenge.ips.example.dedyn.io.\": appending RRSets to zone \"_acme-challenge.ips.example.dedyn.io.\": unexpected status code 404: {\"detail\":\"Not found.\"} (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/115896424/10467030634) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)"}
2023/08/24 03:48:51.202 ERROR   tls.obtain      will retry      {"error": "[*.ips.example.dedyn.io] Obtain: [*.ips.example.dedyn.io] solving challenges: presenting for challenge: adding temporary record for zone \"_acme-challenge.ips.example.dedyn.io.\": appending RRSets to zone \"_acme-challenge.ips.example.dedyn.io.\": unexpected status code 404: {\"detail\":\"Not found.\"} (order=https://acme-staging-v02.api.letsencrypt.org/acme/order/115896424/10467030634) (ca=https://acme-staging-v02.api.letsencrypt.org/directory)", "attempt": 2, "retrying_in": 120, "elapsed": 63.9184038, "max_duration": 2592000}
```

**Comment by znkr** [comment]
Thanks! This brings us one step closer to understanding the issue. For some reason the zone seems to be `_acme-challenge.ips.example.dedyn.io.` where I would expect `example.dedyn.io`. This would explain the 404 error, the question is why is the zone incorrect?

Edit: We actually had that information already, but I didn't understand the log output then. The new error message explained the old one to me. :)

**Comment by znkr** [comment]
My best hypothesis of what's going on there is that your server is using a DNS resolver that gives incorrect information.

You could try to override the resolver (https://caddyserver.com/docs/caddyfile/directives/tls#resolvers) with 8.8.8.8 or 1.1.1.1. Note, that this might not be enough though; there are ways to enforce using a specific DNS resolver.

Before changing the configuration I would try to verify this hypothesis with `dig SOA _acme-challenge.ips.example.dedyn.io`.

**Comment by peterthomassen** [comment]
> the domain was changed to example

This makes it hard to debug: @znkr is now using this name in https://github.com/libdns/desec/issues/1#issuecomment-1692903095, and getting inappropriate results.

@MyAnoneNeko, can you please reproduce the problem with a domain name that you are willing to share? Thanks.

**Comment by MyAnoneNeko** [comment]
> try to override the resolver (...) with 8.8.8.8 or 1.1.1.1

I tried both resolvers and get the same 404 not found error
> Before changing the configuration I would try to verify this hypothesis with `dig SOA _acme-challenge.ips.example.dedyn.io`.

Here's the output
```
; <<>> DiG 9.16.42 <<>> SOA ips.example.dedyn.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42044
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;ips.example.dedyn.io.      IN      SOA

;; ANSWER SECTION:
ips.example.dedyn.io. 86400 IN      SOA     ips.example.dedyn.io. briancunnie.gmail.com. 2022112600 900 900 1800 180
```


> can you please reproduce the problem with a domain name that you are willing to share?

I tried reproducing at plsdebugme.dedyn.io which is identical to my real dedyn.io domain but with A record changed but I get `dedyn.io to plsdebugme.dedyn.io: No delegation NS records were detected in the parent zone (dedyn.io). This results in an NXDOMAIN response to a DS query (for DNSSEC)` full DNSViz report [here](https://dnsviz.net/d/plsdebugme.dedyn.io/dnssec/).

**Comment by znkr** [comment]
That last one is a DNSSEC problem, does it happen with your real domain too?

**Comment by znkr** [comment]
I believe you ran `dig SOA ips.example.dedyn.io`, is that correct? The result is interesting, because the SOA record `ips.example.dedyn.io. 86400 IN      SOA ips.example.dedyn.io` explains that the authoritative zone is ips.example.dedyn.io. This doesn't match the zone you shared above and it confirms my hypothesis that your DNS resolver is not working correctly (under the assumption that the zone you shared is correct). However, the fact that 8.8.8.8 and 1.1.1.1 have apparently the same behavior is refuting the hypothesis, assuming DNS requests are not intercepted.

I don't know what's going on here, but I am certain now that it's DNS issues. Maybe you can share your real DNS zone privately with me?

**Comment by peterthomassen** [comment]
> > can you please reproduce the problem with a domain name that you are willing to share?
> 
> I tried reproducing at plsdebugme.dedyn.io which is identical to my real dedyn.io domain but with A record changed

For this one, I see:

```
$ dig +short NS plsdebugme.dedyn.io
ns1.desec.io.
ns1.desec.org.
```

The second NS record is wrong (it should be `ns2.desec.org`).

deSEC sets these automatically. For what reason did you modify these records?

It is impossible to debug your problem if you do not provide the domain name of the case at hand. You tried to set up an identical domain, but then the NS configuration got messed up. That may prevent understanding the original problem.

I am going to drop out of this conversation now, until the actual problem is shown with the actual domain.

> but I get `dedyn.io to plsdebugme.dedyn.io: No delegation NS records were detected in the parent zone (dedyn.io). This results in an NXDOMAIN response to a DS query (for DNSSEC)` full DNSViz report [here](https://dnsviz.net/d/plsdebugme.dedyn.io/dnssec/).

It takes some time for the DS records to be deployed in the parent domain (usually up to a few minutes); until then, the new domain (`plsdebugme.dedyn.io`) has no DNSSEC protection. That's normal, and the problem goes away after a few minutes as seen [here](https://dnsviz.net/d/plsdebugme.dedyn.io/ZOx5DA/dnssec/). (The remaining problems reported there are because of the messed up NS records.)

> I believe you ran dig SOA ips.example.dedyn.io, is that correct?

@znkr Again, I think s:he's using `example` as a placeholder, so whatever you're querying about this example domain will not tell you anything about what problem s:he has with the real domain.

**Comment by znkr** [comment]
@peterthomassen, I am aware. And I agree, it's not possible to help without a reproducer.

**Comment by MyAnoneNeko** [comment]
Sorry for the trouble. It is reproducible on plsdebugme.dedyn.io and  gets the same 404 not found error on caddy
```
>dig SOA _acme-challenge.ips.plsdebugme.dedyn.io
; <<>> DiG 9.16.42 <<>> SOA _acme-challenge.ips.plsdebugme.dedyn.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 47786
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;_acme-challenge.ips.plsdebugme.dedyn.io. IN SOA

;; ANSWER SECTION:
_acme-challenge.ips.plsdebugme.dedyn.io. 85615 IN SOA _acme-challenge.ips.plsdebugme.dedyn.io. briancunnie.gmail.com. 2022112600 900 900 1800 180
```

> The second NS record is wrong (it should be `ns2.desec.org`).
> 
> deSEC sets these automatically. For what reason did you modify these records?

Thanks for pointing that out, I just copy from my [zonefile](https://github.com/libdns/desec/issues/1#issuecomment-1690965772) I posted which happen to contain that typo. I corrected the NS record and the error is reproducible on plsdebugme zone now.

**Comment by znkr** [comment]
Thanks, this was very helpful.

The response you posted explains why Caddy is using `_acme-challenge.ips.plsdebugme.dedyn.io` as the zone to add the TXT entry to: It's the authoritative zone in DNS. So from that side, everything works as intended.

The question is, why is this happening? IIUC, you configured sslip.io nameservers for `ips.plsdebugme.dedyn.io`. And they handle SOA records by replying with the query (https://github.com/cunnie/sslip.io/blob/main/README.md).

This means, the problem is the DNS zone.

FWIW, adding the TXT record to a desec zone that delegates to a different nameserver would make the ACME challenge fail because the TXT record would not be resolvable. So I am definitely not understanding what you are trying to do here.

**Comment by MyAnoneNeko** [comment]
> FWIW, adding the TXT record to a desec zone that delegates to a different nameserver would make the ACME challenge fail because the TXT record would not be resolvable

Thanks for clarifying that's where my knowledge was lacking.

> So I am definitely not understanding what you are trying to do here.

I was trying to automate wildcard certificate procurement on `ips` subdomain on caddy while using sslip.io nameservers. But it is not possible from what you said. 
I figure out a manual way by creating `ips.example` zone on dedyn.io which allow caddy to pass the DNS challenge and get the certs. Then I delete the `ips.example` zone and add back the NS record to sslip.io nameservers. Again, thanks for you help I learn many things.

**Comment by znkr** [comment]
I have never tried this, but it might be possible to use a wildcard NS record for `*.ips` here. You might also need a NS record for `_acme_challenge.ips` that points to the desec nameservers.

That said, it feels pretty hacky. What is the underlying problem you want to solve? Maybe there's a simpler solution.

**Comment by MyAnoneNeko** [comment]
> use a wildcard NS record for `*.ips` here

Hmm just tried it doesn't look like it's using sslip.io nameservers
```
*.ips.plsdebugme.dedyn.io.      3600    IN      NS      ns-aws.sslip.io.
*.ips.plsdebugme.dedyn.io.      3600    IN      NS      ns-gce.sslip.io.
```


> What is the underlying problem you want to solve?

I want TLS when I access my apps or API through internal IPs. For example, I am running an IRC client available through `100.64.2.3` and `192.168.4.5`. When I'm home, I should be able to connect from any device through `irc-192-168-4-5.ips.example.dedyn.io`. When I'm traveling, I can connect using `irc-100-64-1-2.ips.example.dedyn.io`. Same thing logic for my files, it would be `files-100-64-1-2.ips.example.dedyn.io` and `files-192-168-4-5.ips.example.dedyn.io` and so on.

**Comment by znkr** [comment]
This is an extremely unusual use case. Is there a reason you want use IPs directly instead of a name?

**Comment by MyAnoneNeko** [comment]
May you elaborate what you're asking? I'm not sure what you're asking but I'm open to other ideas. I want to access my apps/api with TLS that are on multiple internal IPs.

**Comment by znkr** [comment]
DNS is intended to abstract away from IPs. So, encoding IPs in DNS names is a bit backwards. So I am wondering why you are doing it.

Resolving one name to different IP addresses based on some context is actually fairly common. In your case, I would take a look at Split DNS. That's a type of configuration to resolve a name differently at home and everywhere else. It's usually implemented by running a DNS server in your local network.

**Comment by MyAnoneNeko** [comment]
> encoding IPs in DNS names is a bit backwards. So I am wondering why you are doing it.

At the time when setting everything up, mapping IP and with name is a 2-in-1 for me. I could specify which device (internal IP) and app I want to access all under one main domain. It's also fairly simple to setup since I only needed to created a NS record point to sslip.io nameservers. The only missing link was TLS since some of the apps (API) I use have that requirement.

> I would take a look at Split DNS

Thanks I'll look into that.
