### ISSUE TITLE
Define minimum TTL to 60s

### ISSUE THREAD

**Issue by IlariStenrothValtori** [libdns/desec#4]
https://github.com/libdns/desec/blob/7f39ae01f41fcfbb3c4de199891add29403c5d75/provider.go#L363C13-L363C13

deSEC allows 60s TTL as minimum. The code sets currently minimum as 3600s. The could should allow TTL of 60s as minimum.

**Comment by peterthomassen** [comment]
The minimum TTL depends on the domain, and usually is 3600s unless a support request was made. The applicable value can be read from the [domain object](https://desec.readthedocs.io/en/latest/dns/domains.html#domain-field-reference) returned when [retrieving a domain](https://desec.readthedocs.io/en/latest/dns/domains.html#retrieving-a-specific-domain) from the API.

Note that when performing a [dynDNS update](https://desec.readthedocs.io/en/latest/dyndns/update-api.html), the backend will use a TTL of 60s for the A/AAAA records, regardless of the domain's minimum TTL setting.

**Comment by IlariStenrothValtori** [comment]
Ok, if that's the generic case then let's keep 3600s.
